export enum ErrorCodeEnum {
    UNAUTHORIZED = 600,
    INVALID_CREDENTIALS = 601,
    INVALID_USER = 602,
    NEW_PASSWORD_NOT_CONFIRMED = 603,
    OLD_PASSWORD_AND_NEW_ARE_MATCHED = 604,
    INCORRECT_PASSWORD = 605,
    USERNAME_OR_EMAIL_ALREADY_EXIST = 606,
    INVALID_TOKEN = 607,
    ALLOWED_FOR_ADMIN_ONLY = 608,
    CAN_NOT_FIND_CAR = 609,
    THIS_CAR_ALREADY_RENT_DOR_NOW = 610,
    START_DATE_MUST_BE_SMALLER_THAN_END_DATE = 611,
    CAR_IN_PREP_PERIOD_NOW_AND_WILL_VALID_IN_24_HOURS = 612
}